### ISSUE TITLE
Installation on windows?

### ISSUE THREAD

**Issue by jlistgarten** [neurospin/pylearn-parsimony#13]
After doing a git clone and then running python setup.py install I get many errors. Should I be able to install this on Windows? Trace is below.

D:\Source\pylearn-parsimony>python setup.py install
C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\dist.py:294: UserWarning: The version specified ('0
x') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
running install
running bdist_egg
running egg_info
creating pylearn_parsimony.egg-info
writing requirements to ./pylearn_parsimony.egg-info\requires.txt
writing ./pylearn_parsimony.egg-info\PKG-INFO
writing top-level names to ./pylearn_parsimony.egg-info\top_level.txt
writing dependency_links to ./pylearn_parsimony.egg-info\dependency_links.txt
writing manifest file './pylearn_parsimony.egg-info\SOURCES.txt'
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    setup(**params)
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\install.py", line 67, in run
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\install.py", line 109, in do_egg_in
ll
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\bdist_egg.py", line 152, in run
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\egg_info.py", line 186, in run
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\egg_info.py", line 209, in find_sou
s
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\egg_info.py", line 293, in run
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\egg_info.py", line 322, in add_defa
s
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\sdist.py", line 120, in add_default
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-20.7.0-py2.7.egg\setuptools\command\build_py.py", line 33, in finalize_
ions
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build_py.py", line 56, in finalize_options
    self.package_dir[name] = convert_path(path)
  File "C:\Users\jennl\AppData\Local\Continuum\Anaconda2\lib\distutils\util.py", line 126, in convert_path
    raise ValueError, "path '%s' cannot end with '/'" % pathname
ValueError: path './' cannot end with '/'

**Comment by tomlof** [comment]
There are two things you could try out immediately:

- Download the release version of pylearn-parsimony and try to install it instead of the master branch (the master branch may be slightly unstable).
- Start the Command window in administrator mode and try to install it again when run as administrator.

Please let us know if any of these worked, it would be great to add Windows installation instructions to the readme.

The reference environment for pylearn-parsimony is Ubuntu 12.04 (in practice it is 14.04 by now), and while we regularly use it and run the unit tests on Windows 7, we have not tested the installation in a Windows environment.

I will, however, test this within a couple of days, and will fix the errors that I find. I will let you know my findings!

**Comment by tomlof** [comment]
I finally got the time to look into this problem. Unfortunately, I could install it on a Windows 7 machine on Python 2.7 without any problems.

I could however infer that the error in your output was because the parameter package_dir contained a slash ("/"), which is not allowed. I have removed this, and it installs fine on all my systems (on Ubuntu 14.04 in both Python 2.7 and Python 3.4 and on Windows 7 in Python 2.7).

Let me know if you still have problems installing, and I'll dig into this further. If so, also let me know what version of Windows you are on and what version of Python you are using.

**Comment by tomlof** [comment]
Did this update solve your problem with the installation?
